### PR TITLE
:hammer: Add CityBuild-Economy

### PR DESCRIPTION
**Pull request by FlorianWip**

### CODE REVIEW

**Comment by Packsolite** [comment]
Shouldn't we give it a proper name?

**Comment by FlorianWip** [comment]
Do you have a suggestion. I wanted to use a selfexplaining Name

**Comment by Packsolite** [comment]
Just use the name of the currency that is displayed ingame..
Idk if you wanna call it dollar, shards, gold or if you really want to call it coins, then i'm fine with CITYBUILD_COINS.

**Comment by FlorianWip** [comment]
> Just use the name of the currency that is displayed ingame..
> Idk if you wanna call it dollar, shards, gold or if you really want to call it coins, then i'm fine with CITYBUILD_COINS.

We (@hyperspacepilot and me) are currently not sure how to name it. We will decide this weekend and I will commit our decision

**Comment by Packsolite** [comment]
Tf?

**Pull request closed without merging**
